version: '3'
services:
  hrnet:
    build : "./HRNet-Human-Pose-Estimation"
    image: hrnet:1.0
    container_name: hrnet
    volumes:
      - "./HRNet-Human-Pose-Estimation:/HRNet-Human-Pose-Estimation"
    depends_on:
      - rabbitmq
    environment:
      - RMQ_PORT=5672

  rabbitmq:
    image: rabbitmq:3.9.29
    container_name: rabbitmq
    environment:
      - PORT=5672
  server:
    image: node_server:1.0
    container_name: node_server
    build : "./server"
    volumes :
      - "./HRNet-Human-Pose-Estimation/data/babypose/images:/server/images"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - publisher
    environment:
      - PORT=5000
      - API_PORT=3001
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pgdb
      - DB_HOST=postgres
      - INF_COST=5
      - IMG_COST=0.1
  
  publisher:
    build: "./publisher"
    image: publisher:1.0
    container_name : publisher
    depends_on:
      - rabbitmq
      - hrnet
    environment:
      - RMQ_PORT=5672
      - API_PORT=3001
    volumes:
      - "./publisher:/publisher"
      
  postgres:
    container_name: postgres
    image: "postgres:13"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pgdb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./server/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  
volumes:
  pg_data: {}
